server:
  port: 52001
  servlet:
    context-path: /
swagger:
  enable: true
  title: Long SoftWare Microservice
  description: account microservice
  version: 0.0.1
  contactName: LELong
  contactEmail: lelong1304@gmail.com
http:
  cors:
    allow:
      credentials: true
      headers: app Origin, Content-Type, Accept, Authorization, Access-Control-Request-Headers
      methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH
      origin: http://localhost:4200
    max:
      age: 3600
    expose:
      headers:
spring:
  application:
    name: account-api
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-246-24-110.eu-west-1.compute.amazonaws.com:5432/d708kvj57mk2n9?ApplicationName=user-msa
    username: cdkkacfbhmxtux
    password: d9ffc46ad0e21b270b1ac26c3281029b6e0f4ac32092619373fc0ea83799d2e2



